### ISSUE TITLE
为什么我用了这个主题之后侧边栏的博主动态出现问题？

### ISSUE THREAD

**Issue by vic9527** [yunfeilangwu/Echo#1]
如图：
![image](https://user-images.githubusercontent.com/9958494/61867241-52c94780-af09-11e9-8bb7-d311eb3c27b4.png)

**Comment by yunfeilangwu** [comment]
你好，请问你使用的typecho的版本是？

**Comment by yunfeilangwu** [comment]
请使用最新版本
