### ISSUE TITLE
user.echo.so的几点建议

### ISSUE THREAD

**Issue by lhuang001** [yunfeilangwu/Echo#11]
感谢作者开源的echo主题~我在使用过程中发现了几个user.echo.so的问题，希望作者在百忙之中抽出时间处理一下。
1.user.echo.so没有采用https。在使用echo主题的网站启用https后，打开网站首页，会报NET::ERR_CERT_DATE_INVALID，如附件1
2.在设置里取消显示echo用户排名后，依然会向user.echo.so发送数据，这里是否可以取消请求？
当使用者已经明确不显示时，再向user.echo.so发送数据并没有实际意义，相反还会增加浏览器请求时间。
3.用户排名算法存在缺陷，https和http被误认为是两个不同站点，如附件echo

本人不熟悉php开发，如果需要我可以提供相关PR。再次感谢作者的开源工作。
![1](https://user-images.githubusercontent.com/21240907/133711379-ebdcd87e-469c-47e9-af99-0e1e7f13d608.png)
![echo](https://user-images.githubusercontent.com/21240907/133711384-73597fa6-c85b-4bbc-a9e1-d091b8a2d1bd.png)

**Comment by yunfeilangwu** [comment]
v3.0版本已经去除该排名统计
