### ISSUE TITLE
主题问题

### ISSUE THREAD

**Issue by yeaman2020** [yunfeilangwu/echo#14]
Parse error: syntax error, unexpected 'echo' (T_ECHO) in /webHome/host1461531/www/usr/themes/Echo1/Library/Init.php on line 31
![1648125575(1)](https://user-images.githubusercontent.com/60549900/159918166-3030ae12-3ee2-4992-84de-80d4a63e18c8.png)

**Comment by yunfeilangwu** [comment]
关键词冲突，使用最新版v3.1就没问题了
