### ISSUE TITLE
启用3.0主题，编辑器中数字列表和普通列表在预览的时候显示不正常，发布后显示正常

### ISSUE THREAD

**Issue by itianjing** [yunfeilangwu/echo#15]
![1](https://user-images.githubusercontent.com/4278919/160330278-f534ef34-a318-4b72-a81e-03f33a42ef60.png)
![2](https://user-images.githubusercontent.com/4278919/160330287-6dae7e9d-cba1-439a-ad0f-194f506de9ad.png)

**Comment by yunfeilangwu** [comment]
已修复
