### ISSUE TITLE
请问最新版本博主动态和归档是如何设置的？

### ISSUE THREAD

**Issue by jasonfanjun** [yunfeilangwu/Echo#2]
请问最新版本博主动态和归档是如何设置的？
感谢指引

**Comment by yunfeilangwu** [comment]
归档页面：后台创建独立页面，自定义模板选择[文章归档]。

博主动态：后台创建独立页面，自定义模板选择[说说动态]。成功创建后，前台访问该页面，可以进行发布动态。发布框只有博主登录的情况下才会显示。

**Comment by iyish** [comment]
创建完成后，发布说说提示“对不起,此内容的反馈被禁止.”
