### ISSUE TITLE
列表前面得图片如何设置?

### ISSUE THREAD

**Issue by js-say** [yunfeilangwu/echo#3]
列表前面得图片如何设置?需要自己每篇提换吗

**Comment by jasonfanjun** [comment]
默认是第一张文章图片

----------

该邮件从移动设备发送




--------------原始邮件--------------
发件人："Shier Chan "<notifications@github.com>;
发送时间：2019年7月29日(星期一) 晚上11:28
收件人："yunfeilangwu/echo" <echo@noreply.github.com>;
抄送："Subscribed "<subscribed@noreply.github.com>;
主题：[yunfeilangwu/echo] 列表前面得图片如何设置? (#3)
-----------------------------------

 
列表前面得图片如何设置?需要自己每篇提换吗

**Comment by js-say** [comment]
文章我得是md写的，然后也有图片但是列表展示得那个图片都是一张。00.png

**Comment by js-say** [comment]
刚刚看到您网站留言说是文章附件得图片，我先试试

**Comment by jasonfanjun** [comment]
我不是作者，但尝试过上传附件没问题。

----------

该邮件从移动设备发送




--------------原始邮件--------------
发件人："Shier Chan "<notifications@github.com>;
发送时间：2019年7月29日(星期一) 晚上11:59
收件人："yunfeilangwu/echo" <echo@noreply.github.com>;
抄送："jasonfanjun "<jasonfan@shuohui.cn>;"Comment "<comment@noreply.github.com>;
主题：Re: [yunfeilangwu/echo] 列表前面得图片如何设置? (#3)
-----------------------------------

 
刚刚看到您网站留言说是文章附件得图片，我先试试

**Comment by js-say** [comment]
好的， 感谢。
