### ISSUE TITLE
启用2.0最新主题后，导航栏，侧边栏都不显示，设置外观保存后没有任何反应

### ISSUE THREAD

**Issue by 1244453393** [yunfeilangwu/Echo#7]
![QQ截图20200609230102](https://user-images.githubusercontent.com/24578032/84164638-59bb6300-aaa5-11ea-943d-0207d78b41b1.jpg)

**Comment by ranlychan** [comment]
+1

**Comment by jiang1912** [comment]
+1

**Comment by yunfeilangwu** [comment]
该问题应该是后台layui没加载上，导致设置外观保存不成功。请使用最新版。
